In [1]:
import pandas as pd
import numpy as np

In [2]:
data_book1=pd.read_csv(r"C:\Users\Ghalamkarian\PycharmProjects\pythonProject3\anime.csv")

In [3]:
data_book1.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [4]:
a=data_book1.drop('type',axis=1)

In [5]:
b=a.drop('episodes',axis=1)

In [6]:
c=b.drop('genre',axis=1)

In [7]:
d=c.drop('rating',axis=1)

In [8]:
data_book=d.drop('members',axis=1)

In [9]:
data_book.head()

   anime_id                              name
0     32281                    Kimi no Na wa.
1      5114  Fullmetal Alchemist: Brotherhood
2     28977                          Gintama°
3      9253                       Steins;Gate
4      9969                     Gintama&#039;

In [10]:
data_book.shape

(12294, 2)

In [11]:
data_book.dtypes

anime_id     int64
name        object
dtype: object

In [12]:
data_book.isnull().sum()

anime_id    0
name        0
dtype: int64

In [13]:
datauser=pd.read_csv(r"C:\Users\Ghalamkarian\PycharmProjects\pythonProject3\anime_rating.csv")

In [14]:
datauser.shape

(1048575, 3)

In [15]:
datauser.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [16]:
datauser.tail()

         user_id  anime_id  rating
1048570    10093     21405       7
1048571    10093     21431       7
1048572    10093     21507       6
1048573    10093     21561       8
1048574    10093     21603       8

In [17]:
datauser[datauser['anime_id']==2294]

        user_id  anime_id  rating
63882       661      2294       7
84247       871      2294      -1
92001       952      2294       9
125809     1280      2294      10
149313     1504      2294       9
152833     1530      2294      10
237421     2447      2294      10
355388     3615      2294      -1
482064     4942      2294       9
484006     4950      2294       7
486916     4979      2294       7
502664     5102      2294      -1
511499     5165      2294      -1
519302     5244      2294       9
535648     5374      2294       7
538062     5388      2294      -1
561117     5552      2294      -1
564006     5570      2294       5
565425     5577      2294      -1
568461     5598      2294      -1
571905     5630      2294       9
577287     5674      2294       8
580902     5705      2294      -1
582141     5706      2294       9
617846     5962      2294       8
633993     6092      2294      -1
637461     6113      2294       6
639368     6125      2294       5
652913     6237      2294       8
670441     6384      2294       9
671025     6385      2294       6
672658     6392      2294      10
702483     6618      2294       6
708161     6674      2294      -1
743072     6940      2294       6
803107     7421      2294       7
809080     7460      2294       9
810820     7477      2294       9
814713     7511      2294       8
828736     7613      2294      -1
837238     7672      2294      -1
900943     8149      2294      -1
908905     8215      2294      10
911468     8221      2294      -1
927449     8372      2294       6
933598     8428      2294      10
939969     8494      2294      -1
972647     8999      2294       9

In [18]:
#datauser['rating']+=1

In [19]:
datauser.dtypes

user_id     int64
anime_id    int64
rating      int64
dtype: object

In [20]:
user1=[{'anime_id': 20,'rating':4},
      {'anime_id':  11757 ,'rating':3},
     
     {'anime_id':  1535  ,'rating':4.5},
     {'anime_id': 226,'rating':5},
     
     ]
user=pd.DataFrame(user1)
user

   anime_id  rating
0        20     4.0
1     11757     3.0
2      1535     4.5
3       226     5.0

In [21]:
user.dtypes

anime_id      int64
rating      float64
dtype: object

In [22]:
t=datauser[datauser['anime_id'].isin(user['anime_id'].tolist())]
#print(len(t))
t

         user_id  anime_id  rating
0              1        20      -1
3              1       226      -1
83             1     11757      10
156            3        20       8
173            3      1535      10
...          ...       ...     ...
1048405    10092      1535       9
1048428    10092     11757       8
1048465    10093        20       7
1048480    10093      1535      10
1048518    10093     11757       8

[17051 rows x 3 columns]

In [23]:
#groupby based on users
user_group=t.groupby(['user_id'])
user_group.head(20)

         user_id  anime_id  rating
0              1        20      -1
3              1       226      -1
83             1     11757      10
156            3        20       8
173            3      1535      10
...          ...       ...     ...
1048405    10092      1535       9
1048428    10092     11757       8
1048465    10093        20       7
1048480    10093      1535      10
1048518    10093     11757       8

[17051 rows x 3 columns]

In [24]:
#u_group=t.groupby(['anime_id'])
#u_group.head(20)

In [25]:
#finding the user reading the most number of given amime

user_sorting=sorted(user_group,reverse=True,key=lambda x:len(x[1]))


#: This groups the data by the 'User-ID' column, creating a group for each unique user ID.

In [26]:
#finding the user reading the most number of given amime

#u_sorting=sorted(u_group,reverse=False,key=lambda x:len(x[1]))
#u_sorting

In [27]:
user_sorting=user_sorting[:200]
user_sorting

[((38,),
        user_id  anime_id  rating
  3383       38        20       6
  3393       38       226       9
  3404       38      1535       6
  3514       38     11757       9),
 ((39,),
        user_id  anime_id  rating
  3636       39        20      10
  3644       39       226       8
  3654       39      1535      10
  3696       39     11757      -1),
 ((50,),
        user_id  anime_id  rating
  4858       50        20      10
  4869       50       226       7
  4901       50      1535       8
  4934       50     11757       7),
 ((79,),
        user_id  anime_id  rating
  6976       79        20       9
  6984       79       226       9
  7005       79      1535       9
  7047       79     11757       6),
 ((80,),
        user_id  anime_id  rating
  7085       80        20       9
  7094       80       226      10
  7125       80      1535      10
  7173       80     11757       9),
 ((88,),
        user_id  anime_id  rating
  7467       88        20       9
  7471       88       226      10
  7487       88      1535      10
  7502       88     11757      10),
 ((90,),
        user_id  anime_id  rating
  7579       90        20      -1
  7585       90       226      -1
  7591       90      1535      -1
  7635       90     11757      10),
 ((97,),
        user_id  anime_id  rating
  7964       97        20       6
  7965       97       226       7
  7973       97      1535      10
  8000       97     11757       9),
 ((99,),
        user_id  anime_id  rating
  8142       99        20       5
  8153       99       226       4
  8183       99      1535       6
  8231       99     11757       2),
 ((104,),
        user_id  anime_id  rating
  8417      104        20       9
  8425      104       226      10
  8437      104      1535      10
  8466      104     11757       8),
 ((108,),
        user_id  anime_id  rating
  8696      108        20       6
  8716      108       226       7
  8739      108      1535       9
  8815      108     11757       8),
 ((112,),
        user_id  anime_id  rating
  9111      112        20      10
  9116      112       226       9
  9127      112      1535      10
  9157      112     11757       6),
 ((118,),
        user_id  anime_id  rating
  9210      118        20       7
  9213      118       226       8
  9222      118      1535       9
  9243      118     11757       6),
 ((129,),
         user_id  anime_id  rating
  10388      129        20       9
  10406      129       226       9
  10444      129      1535      10
  10573      129     11757       8),
 ((173,),
         user_id  anime_id  rating
  13625      173        20      10
  13630      173       226      10
  13640      173      1535      10
  13674      173     11757       8),
 ((185,),
         user_id  anime_id  rating
  14292      185        20       7
  14306      185       226       8
  14325      185      1535       9
  14354      185     11757       8),
 ((187,),
         user_id  anime_id  rating
  14420      187        20       6
  14425      187       226       7
  14438      187      1535       8
  14456      187     11757      10),
 ((189,),
         user_id  anime_id  rating
  14513      189        20       8
  14521      189       226      10
  14545      189      1535      10
  14611      189     11757       6),
 ((190,),
         user_id  anime_id  rating
  14670      190        20       9
  14674      190       226       8
  14711      190      1535      10
  14753      190     11757       7),
 ((198,),
         user_id  anime_id  rating
  15025      198        20      -1
  15036      198       226      -1
  15048      198      1535      -1
  15164      198     11757      -1),
 ((202,),
         user_id  anime_id  rating
  16081      202        20       6
  16095      202       226       6
  16112      202      1535       9
  16167      202     11757       7),
 ((209,),
         user_id  anime_id  rating
  16329      209        20       9
  16333      209       226       9
  16335      209      1535       8
  16347      209     11757       8),
 ((214,),
         user_id  anime_id  rating
  16825      214        20       7
  16827      214       226       5
  16836      214      1535       9
  16863      214     11757      10),
 ((219,),
         user_id  anime_id  rating
  17083      219        20       9
  17090      219       226       9
  17098      219      1535      10
  17138      219     11757       8),
 ((226,),
         user_id  anime_id  rating
  17306      226        20       7
  17357      226       226       8
  17470      226      1535       8
  17745      226     11757       8),
 ((236,),
         user_id  anime_id  rating
  19080      236        20       7
  19084      236       226      10
  19092      236      1535       9
  19124      236     11757       8),
 ((248,),
         user_id  anime_id  rating
  20038      248        20       9
  20064      248       226       9
  20114      248      1535      10
  20314      248     11757      10),
 ((250,),
         user_id  anime_id  rating
  20519      250        20       7
  20527      250       226       4
  20536      250      1535       7
  20618      250     11757       8),
 ((253,),
         user_id  anime_id  rating
  20841      253        20       6
  20844      253       226      10
  20850      253      1535       9
  20871      253     11757       4),
 ((261,),
         user_id  anime_id  rating
  21446      261        20       7
  21462      261       226      10
  21492      261      1535      10
  21617      261     11757       6),
 ((268,),
         user_id  anime_id  rating
  21958      268        20       8
  21959      268       226       8
  21965      268      1535       9
  21997      268     11757       9),
 ((269,),
         user_id  anime_id  rating
  22010      269        20       7
  22024      269       226       7
  22045      269      1535      10
  22093      269     11757       7),
 ((270,),
         user_id  anime_id  rating
  22111      270        20      -1
  22129      270       226      -1
  22159      270      1535      -1
  22320      270     11757      -1),
 ((271,),
         user_id  anime_id  rating
  22402      271        20       1
  22408      271       226      10
  22444      271      1535       9
  22602      271     11757       8),
 ((273,),
         user_id  anime_id  rating
  23041      273        20       5
  23043      273       226       5
  23049      273      1535       8
  23088      273     11757       7),
 ((281,),
         user_id  anime_id  rating
  23603      281        20       8
  23610      281       226       7
  23624      281      1535       8
  23673      281     11757       7),
 ((282,),
         user_id  anime_id  rating
  23756      282        20       9
  23759      282       226      10
  23774      282      1535       9
  23869      282     11757      10),
 ((288,),
         user_id  anime_id  rating
  24387      288        20       8
  24419      288       226      10
  24480      288      1535       9
  24591      288     11757       8),
 ((293,),
         user_id  anime_id  rating
  24986      293        20       8
  24999      293       226       8
  25007      293      1535       9
  25057      293     11757       7),
 ((294,),
         user_id  anime_id  rating
  25093      294        20      10
  25129      294       226       7
  25221      294      1535      10
  25554      294     11757      10),
 ((296,),
         user_id  anime_id  rating
  25858      296        20      10
  25878      296       226       6
  25939      296      1535      10
  26103      296     11757       9),
 ((298,),
         user_id  anime_id  rating
  26261      298        20       9
  26265      298       226       8
  26273      298      1535      10
  26343      298     11757       7),
 ((312,),
         user_id  anime_id  rating
  27317      312        20       9
  27322      312       226       4
  27336      312      1535      10
  27379      312     11757       5),
 ((322,),
         user_id  anime_id  rating
  28333      322        20       9
  28334      322       226       9
  28340      322      1535      10
  28381      322     11757       9),
 ((340,),
         user_id  anime_id  rating
  29387      340        20       6
  29392      340       226       9
  29399      340      1535       9
  29435      340     11757       7),
 ((342,),
         user_id  anime_id  rating
  29648      342        20       9
  29665      342       226       7
  29712      342      1535       6
  30044      342     11757      -1),
 ((343,),
         user_id  anime_id  rating
  30907      343        20       8
  30916      343       226       8
  30923      343      1535      10
  30935      343     11757       8),
 ((349,),
         user_id  anime_id  rating
  31299      349        20       9
  31311      349       226       9
  31319      349      1535      10
  31346      349     11757       9),
 ((352,),
         user_id  anime_id  rating
  31504      352        20       7
  31543      352       226       8
  31594      352      1535       8
  31728      352     11757       8),
 ((354,),
         user_id  anime_id  rating
  31862      354        20       8
  31865      354       226       7
  31870      354      1535       8
  31912      354     11757       5),
 ((375,),
         user_id  anime_id  rating
  33761      375        20      -1
  33777      375       226      -1
  33840      375      1535      -1
  33913      375     11757      -1),
 ((379,),
         user_id  anime_id  rating
  34068      379        20       9
  34079      379       226       6
  34094      379      1535      10
  34185      379     11757      -1),
 ((390,),
         user_id  anime_id  rating
  35049      390        20       6
  35058      390       226       7
  35064      390      1535       8
  35077      390     11757       8),
 ((395,),
         user_id  anime_id  rating
  36017      395        20       7
  36029      395       226       7
  36073      395      1535       9
  36163      395     11757       7),
 ((418,),
         user_id  anime_id  rating
  37800      418        20      10
  37810      418       226      10
  37832      418      1535      10
  37940      418     11757      10),
 ((427,),
         user_id  anime_id  rating
  38665      427        20       8
  38671      427       226       6
  38680      427      1535       9
  38738      427     11757       9),
 ((431,),
         user_id  anime_id  rating
  39118      431        20      -1
  39143      431       226      -1
  39166      431      1535      -1
  39296      431     11757      -1),
 ((458,),
         user_id  anime_id  rating
  42774      458        20       7
  42778      458       226       9
  42782      458      1535      10
  42810      458     11757       9),
 ((460,),
         user_id  anime_id  rating
  42941      460        20       8
  42978      460       226       7
  43060      460      1535       8
  43233      460     11757       8),
 ((471,),
         user_id  anime_id  rating
  44170      471        20       6
  44171      471       226       6
  44174      471      1535      -1
  44184      471     11757       7),
 ((478,),
         user_id  anime_id  rating
  44688      478        20       9
  44710      478       226       9
  44790      478      1535       9
  45140      478     11757       9),
 ((492,),
         user_id  anime_id  rating
  46083      492        20       5
  46092      492       226       6
  46105      492      1535       9
  46219      492     11757      10),
 ((501,),
         user_id  anime_id  rating
  47381      501        20       8
  47387      501       226       8
  47404      501      1535      10
  47445      501     11757      10),
 ((511,),
         user_id  anime_id  rating
  48315      511        20       7
  48345      511       226      10
  48417      511      1535      10
  48699      511     11757       8),
 ((540,),
         user_id  anime_id  rating
  51066      540        20       9
  51072      540       226       9
  51079      540      1535      10
  51177      540     11757      10),
 ((551,),
         user_id  anime_id  rating
  52392      551        20       6
  52413      551       226       6
  52441      551      1535      10
  52575      551     11757      10),
 ((552,),
         user_id  anime_id  rating
  52672      552        20       8
  52682      552       226       9
  52721      552      1535      10
  52817      552     11757       9),
 ((559,),
         user_id  anime_id  rating
  53586      559        20       8
  53596      559       226       7
  53633      559      1535       9
  53685      559     11757       7),
 ((567,),
         user_id  anime_id  rating
  54624      567        20       9
  54640      567       226       6
  54692      567      1535      10
  54825      567     11757       8),
 ((571,),
         user_id  anime_id  rating
  55065      571        20      10
  55071      571       226       8
  55082      571      1535      10
  55117      571     11757      10),
 ((579,),
         user_id  anime_id  rating
  56186      579        20       9
  56187      579       226      10
  56191      579      1535      10
  56208      579     11757      10),
 ((581,),
         user_id  anime_id  rating
  56255      581        20       6
  56269      581       226       7
  56314      581      1535       8
  56406      581     11757      10),
 ((585,),
         user_id  anime_id  rating
  56480      585        20       8
  56498      585       226       9
  56535      585      1535       9
  56623      585     11757       6),
 ((590,),
         user_id  anime_id  rating
  56999      590        20       8
  57000      590       226       9
  57009      590      1535       9
  57049      590     11757      10),
 ((592,),
         user_id  anime_id  rating
  57082      592        20       8
  57090      592       226      10
  57124      592      1535      10
  57183      592     11757       9),
 ((593,),
         user_id  anime_id  rating
  57211      593        20       7
  57215      593       226       8
  57227      593      1535       9
  57322      593     11757       9),
 ((612,),
         user_id  anime_id  rating
  59002      612        20       8
  59011      612       226       7
  59038      612      1535       8
  59073      612     11757       7),
 ((613,),
         user_id  anime_id  rating
  59086      613        20      10
  59102      613       226      10
  59116      613      1535      -1
  59176      613     11757      10),
 ((614,),
         user_id  anime_id  rating
  59187      614        20       6
  59204      614       226       6
  59233      614      1535       5
  59283      614     11757       5),
 ((617,),
         user_id  anime_id  rating
  59377      617        20      10
  59381      617       226      10
  59387      617      1535      10
  59415      617     11757      10),
 ((654,),
         user_id  anime_id  rating
  62484      654        20       9
  62491      654       226       9
  62511      654      1535      10
  62545      654     11757      10),
 ((656,),
         user_id  anime_id  rating
  62683      656        20       7
  62691      656       226       7
  62722      656      1535       9
  62838      656     11757       7),
 ((662,),
         user_id  anime_id  rating
  64372      662        20       8
  64384      662       226       9
  64416      662      1535      10
  64509      662     11757       9),
 ((666,),
         user_id  anime_id  rating
  64762      666        20      10
  64769      666       226       8
  64779      666      1535       7
  64812      666     11757       7),
 ((694,),
         user_id  anime_id  rating
  67359      694        20       8
  67376      694       226       8
  67403      694      1535       9
  67486      694     11757       9),
 ((702,),
         user_id  anime_id  rating
  67826      702        20       9
  67841      702       226       9
  67901      702      1535      10
  68001      702     11757       7),
 ((735,),
         user_id  anime_id  rating
  69815      735        20       7
  69818      735       226       6
  69833      735      1535       6
  69905      735     11757       8),
 ((747,),
         user_id  anime_id  rating
  71656      747        20       6
  71665      747       226       8
  71675      747      1535       8
  71703      747     11757       7),
 ((760,),
         user_id  anime_id  rating
  72677      760        20      -1
  72689      760       226      -1
  72720      760      1535      -1
  72818      760     11757      -1),
 ((764,),
         user_id  anime_id  rating
  73379      764        20      -1
  73380      764       226      -1
  73385      764      1535      -1
  73428      764     11757      -1),
 ((773,),
         user_id  anime_id  rating
  74561      773        20       8
  74565      773       226       8
  74577      773      1535       8
  74630      773     11757       9),
 ((783,),
         user_id  anime_id  rating
  75385      783        20       7
  75392      783       226       7
  75402      783      1535       8
  75484      783     11757      10),
 ((784,),
         user_id  anime_id  rating
  75630      784        20       7
  75644      784       226       8
  75673      784      1535       7
  75763      784     11757       7),
 ((788,),
         user_id  anime_id  rating
  76596      788        20       8
  76606      788       226       8
  76641      788      1535      10
  76716      788     11757       9),
 ((795,),
         user_id  anime_id  rating
  77324      795        20      10
  77342      795       226       9
  77376      795      1535      10
  77496      795     11757       6),
 ((804,),
         user_id  anime_id  rating
  78275      804        20      -1
  78312      804       226      10
  78437      804      1535      10
  78726      804     11757      10),
 ((813,),
         user_id  anime_id  rating
  79514      813        20       7
  79525      813       226       8
  79561      813      1535       7
  79690      813     11757       7),
 ((814,),
         user_id  anime_id  rating
  79855      814        20       7
  79880      814       226       8
  79921      814      1535       9
  80093      814     11757       5),
 ((819,),
         user_id  anime_id  rating
  80303      819        20       7
  80330      819       226      10
  80372      819      1535      10
  80503      819     11757      10),
 ((862,),
         user_id  anime_id  rating
  83664      862        20       6
  83684      862       226       8
  83710      862      1535       7
  83801      862     11757      10),
 ((893,),
         user_id  anime_id  rating
  85281      893        20       9
  85289      893       226       8
  85301      893      1535      10
  85358      893     11757      10),
 ((894,),
         user_id  anime_id  rating
  85455      894        20       8
  85469      894       226       9
  85486      894      1535      10
  85585      894     11757       7),
 ((897,),
         user_id  anime_id  rating
  85802      897        20       8
  85804      897       226       8
  85808      897      1535       7
  85843      897     11757       5),
 ((920,),
         user_id  anime_id  rating
  87611      920        20       8
  87614      920       226       9
  87633      920      1535       8
  87767      920     11757       7),
 ((925,),
         user_id  anime_id  rating
  88311      925        20      -1
  88318      925       226      -1
  88334      925      1535      -1
  88369      925     11757      -1),
 ((932,),
         user_id  anime_id  rating
  88931      932        20      10
  88936      932       226      -1
  88952      932      1535      10
  89055      932     11757      -1),
 ((937,),
         user_id  anime_id  rating
  89662      937        20      10
  89665      937       226       9
  89689      937      1535      10
  89821      937     11757      10),
 ((938,),
         user_id  anime_id  rating

In [28]:
#finding which animas user 185 have watched.
r=user_group.get_group(2447)
r

        user_id  anime_id  rating
237395     2447        20       8
237401     2447       226       9
237415     2447      1535       9

In [29]:
#creating a dic contains similarity between users and the target user
import math
pearsonCorrelationDict = {}

#For every user group in our subset
for name, group in user_sorting:
    name=name[0]
    #Let's start by sorting the input and current user group so the values aren't mixed up later on
    group = group.sort_values(by='anime_id')
    inputMovies= user.sort_values(by='anime_id')
    #Get the N for the formula
    nRatings = len(group)
    #Get the review scores for the movies that they both have in common
    temp_df = inputMovies[inputMovies['anime_id'].isin(group['anime_id'].tolist())]
    #And then store them in a temporary buffer variable in a list format to facilitate future calculations
    tempRatingList = temp_df['rating'].tolist()
    #Let's also put the current user group reviews in a list format
    tempGroupList = group['rating'].tolist()
    #Now let's calculate the pearson correlation between two users, so called, x and y
    Sxx = sum([i**2 for i in tempRatingList]) - pow(sum(tempRatingList),2)/float(nRatings)
    Syy = sum([i**2 for i in tempGroupList]) - pow(sum(tempGroupList),2)/float(nRatings)
    Sxy = sum( i*j for i, j in zip(tempRatingList, tempGroupList)) - sum(tempRatingList)*sum(tempGroupList)/float(nRatings)
    
    #If the denominator is different than zero, then divide, else, 0 correlation.
    if Sxx != 0 and Syy != 0:
        pearsonCorrelationDict[name] = Sxy/math.sqrt(Sxx*Syy)
    else:
        pearsonCorrelationDict[name] = 0

In [30]:
name

1731

In [31]:
group

        user_id  anime_id  rating
173346     1731        20      10
173365     1731       226       9
173384     1731      1535       8
173464     1731     11757      -1

In [32]:
 temp_df

   anime_id  rating
0        20     4.0
3       226     5.0
2      1535     4.5
1     11757     3.0

In [33]:
len(tempRatingList),len(group)

(4, 4)

In [34]:
tempGroupList

[10, 9, 8, -1]

In [35]:
Sxx,Syy
print(Sxy)

10.75

In [36]:
pearsonCorrelationDict

{38: -0.1690308509457033,
 39: 0.7897159446269911,
 50: 0.0,
 79: 0.8783100656536799,
 80: 0.8451542547285166,
 88: 0.09759000729485333,
 90: -0.8783100656536799,
 97: -0.21380899352993948,
 99: 0.6571428571428571,
 104: 0.9683296637314885,
 108: -0.07559289460184544,
 112: 0.7475319302283772,
 118: 0.8315218406202999,
 129: 0.7171371656006361,
 173: 0.8783100656536799,
 185: 0.23904572186687872,
 187: -0.6571428571428571,
 189: 0.9683296637314885,
 190: 0.5291502622129182,
 198: 0,
 202: 0.0,
 209: 0.50709255283711,
 214: -0.7702079842374077,
 219: 0.7171371656006361,
 226: 0.09759000729485333,
 236: 0.680336051416609,
 248: -0.50709255283711,
 250: -0.8451542547285166,
 253: 0.9745586289152093,
 261: 0.9230930832457441,
 268: -0.50709255283711,
 269: 0.29277002188455997,
 270: 0,
 271: 0.28685486624025447,
 273: -0.29277002188455997,
 281: 0.1690308509457033,
 282: -0.1690308509457033,
 288: 0.8664002254439634,
 293: 0.7171371656006361,
 294: -0.6831300510639732,
 296: -0.4897622991151437,
 298: 0.5291502622129182,
 312: 0.06629935441317959,
 322: 0.29277002188455997,
 340: 0.6831300510639732,
 342: 0.7516710982200312,
 343: 0.29277002188455997,
 349: 0.29277002188455997,
 352: 0.09759000729485333,
 354: 0.6900655593423543,
 375: 0,
 379: 0.7073797427026733,
 390: -0.2548235957188128,
 395: 0.29277002188455997,
 418: 0,
 427: -0.6900655593423543,
 431: 0,
 458: 0.19389168358237033,
 460: -0.6831300510639733,
 471: -0.39597275801134096,
 478: 0,
 492: -0.5329480400990121,
 501: -0.50709255283711,
 511: 0.6831300510639732,
 540: -0.50709255283711,
 551: -0.50709255283711,
 552: 0.23904572186687872,
 559: 0.2548235957188128,
 567: -0.2571428571428571,
 571: -0.6831300510639733,
 579: 0.09759000729485333,
 581: -0.6571428571428571,
 585: 0.9660917830792959,
 590: -0.47809144373375745,
 592: 0.5606119105813882,
 593: -0.2548235957188128,
 612: 0.1690308509457033,
 613: -0.2927700218845599,
 614: 0.50709255283711,
 617: 0,
 654: -0.50709255283711,
 656: 0.29277002188455997,
 662: 0.23904572186687872,
 666: 0.13801311186847084,
 694: -0.50709255283711,
 702: 0.8143450710459553,
 735: -0.9683296637314885,
 747: 0.5606119105813882,
 760: 0,
 764: 0,
 773: -0.8783100656536799,
 783: -0.8280786712108251,
 784: 0.6831300510639733,
 788: -0.15289415743128767,
 795: 0.7475319302283772,
 804: 0.09759000729485331,
 813: 0.6831300510639733,
 814: 0.8857142857142857,
 819: 0.09759000729485331,
 862: -0.5428571428571428,
 893: -0.6625413488689132,
 894: 0.8315218406202999,
 897: 0.8280786712108251,
 920: 0.9561828874675149,
 925: 0,
 932: 0.1690308509457033,
 937: -0.6831300510639733,
 938: 0.9694584179118516,
 953: 0,
 958: 0.29277002188455997,
 966: 0.932294445082039,
 977: -0.09759000729485331,
 1000: 0.8451542547285166,
 1010: -0.6831300510639733,
 1016: -0.45776119097753637,
 1028: -0.6831300510639733,
 1036: -0.5501485601695769,
 1042: 0.7171371656006361,
 1043: 0.23904572186687872,
 1044: -0.41403933560541256,
 1046: -0.50709255283711,
 1048: -0.09759000729485333,
 1058: 0.1690308509457033,
 1064: -0.4016771562027471,
 1066: -0.9827076298239908,
 1072: -0.15289415743128767,
 1081: 0.8783100656536799,
 1114: 0.4857142857142857,
 1132: -0.4265617038812147,
 1138: 0.29277002188455997,
 1143: 0,
 1153: 0.19389168358237033,
 1160: 0,
 1170: 0,
 1176: 0.8451542547285166,
 1189: -0.29277002188455997,
 1190: -0.8783100656536799,
 1191: 0.2777940953522052,
 1194: -0.0563436169819011,
 1212: 0,
 1216: -0.23904572186687872,
 1232: -0.13801311186847084,
 1252: 0,
 1260: 0.6625413488689132,
 1266: -0.3578300267477955,
 1272: 0.7228063223242011,
 1274: -0.41403933560541256,
 1281: -0.038778336716474064,
 1284: -0.6625413488689132,
 1287: 0.09759000729485333,
 1289: 0.581675050747111,
 1297: -0.2548235957188128,
 1301: 0.09759000729485333,
 1305: 0.09759000729485333,
 1307: 0.29277002188455997,
 1308: -0.2916330466305957,
 1327: 0.29277002188455997,
 1338: -0.50709255283711,
 1340: 0.6831300510639733,
 1344: 0.022388683141982252,
 1349: 0.8451542547285166,
 1358: -0.4265617038812147,
 1359: -0.6486749731408025,
 1385: -0.6900655593423543,
 1395: 0.11002971203391539,
 1418: 0.09759000729485333,
 1437: 0.20203050891044214,
 1444: -0.37796447300922725,
 1450: -0.8783100656536799,
 1451: -0.41403933560541256,
 1460: 0,
 1501: -0.9035079029052513,
 1524: 0,
 1526: -0.15289415743128767,
 1528: 0.29277002188455997,
 1530: 0.581675050747111,
 1549: 0.050964719143762556,
 1554: -0.5606119105813882,
 1605: 0,
 1606: 0.09759000729485331,
 1609: 0,
 1617: 0.8250791525837599,
 1623: -0.41403933560541256,
 1626: -0.8451542547285166,
 1630: -0.8451542547285166,
 1632: -0.09759000729485331,
 1643: -0.8664002254439634,
 1645: -0.50709255283711,
 1647: 0.6571428571428571,
 1656: -0.6831300510639733,
 1665: 0.1690308509457033,
 1666: -0.50709255283711,
 1682: 0.29277002188455997,
 1705: 0.7171371656006361,
 1710: 0.9660917830792959,
 1718: -0.2548235957188128,
 1728: -0.37796447300922725,
 1729: 0,
 1730: -0.50709255283711,
 1731: 0.828302688169126}

In [37]:
#creating similarity matrix
pearsonDF = pd.DataFrame.from_dict(pearsonCorrelationDict, orient='index')
pearsonDF.columns = ['similarityIndex']
pearsonDF['userId'] = pearsonDF.index
pearsonDF.index = range(len(pearsonDF))
pearsonDF.head()

   similarityIndex  userId
0        -0.169031      38
1         0.789716      39
2         0.000000      50
3         0.878310      79
4         0.845154      80

In [38]:
pearsonDF['similarityIndex']=round(pearsonDF['similarityIndex'], 2)

In [39]:
#sorting similarity matrix
topUsers=pearsonDF.sort_values(by='similarityIndex', ascending=False)[0:50]
topUsers.head()

     similarityIndex  userId
72              0.97     585
194             0.97    1710
28              0.97     253
9               0.97     104
107             0.97     938

In [40]:
topUsers.dtypes

similarityIndex    float64
userId               int64
dtype: object

In [41]:
topUsersRating=topUsers.merge(datauser, left_on='userId', right_on='user_id', how='inner')
topUsersRating.head()

   similarityIndex  userId  user_id  anime_id  rating
0             0.97     585      585         1       8
1             0.97     585      585         5       7
2             0.97     585      585         6       8
3             0.97     585      585        20       8
4             0.97     585      585        30       8

In [42]:
#Multiplies the similarity by the user's ratings
topUsersRating['weightedRating'] = topUsersRating['similarityIndex']*topUsersRating['rating']
topUsersRating.head()

   similarityIndex  userId  user_id  anime_id  rating  weightedRating
0             0.97     585      585         1       8            7.76
1             0.97     585      585         5       7            6.79
2             0.97     585      585         6       8            7.76
3             0.97     585      585        20       8            7.76
4             0.97     585      585        30       8            7.76

In [43]:
#Applies a sum to the topUsers after grouping it up by userId
tempTopUsersRating = topUsersRating.groupby('anime_id').sum()[['similarityIndex','weightedRating']]
tempTopUsersRating.columns = ['sum_similarityIndex','sum_weightedRating']
tempTopUsersRating.head()

          sum_similarityIndex  sum_weightedRating
anime_id
1                       18.37              148.35
5                        6.04               32.54
6                        9.12               75.25
7                        1.47               12.07
15                       0.81                5.67

In [44]:
#Creates an empty dataframe
recommendation_df = pd.DataFrame()
#Now we take the weighted average
recommendation_df['weighted average recommendation score'] = tempTopUsersRating['sum_weightedRating']/tempTopUsersRating['sum_similarityIndex']
recommendation_df['anime_id'] = tempTopUsersRating.index
recommendation_df.head()

          weighted average recommendation score  anime_id
anime_id
1                                      8.075667         1
5                                      5.387417         5
6                                      8.251096         6
7                                      8.210884         7
15                                     7.000000        15

In [45]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(50)

          weighted average recommendation score  anime_id
anime_id
2294                                  10.000000      2294
2391                                  10.000000      2391
6115                                  10.000000      6115
6893                                  10.000000      6893
302                                   10.000000       302
1576                                  10.000000      1576
5902                                  10.000000      5902
2356                                  10.000000      2356
5774                                  10.000000      5774
8634                                  10.000000      8634
12695                                 10.000000     12695
996                                   10.000000       996
17121                                 10.000000     17121
135                                   10.000000       135
2252                                  10.000000      2252
5460                                  10.000000      5460
532                                   10.000000       532
740                                   10.000000       740
719                                   10.000000       719
18429                                 10.000000     18429
149                                   10.000000       149
1365                                  10.000000      1365
32935                                 10.000000     32935
160                                   10.000000       160
3247                                  10.000000      3247
6438                                  10.000000      6438
1468                                  10.000000      1468
15775                                 10.000000     15775
10389                                 10.000000     10389
1913                                  10.000000      1913
1506                                  10.000000      1506
8310                                  10.000000      8310
6802                                  10.000000      6802
3002                                   9.747475      3002
170                                    9.636735       170
1566                                   9.605442      1566
8142                                   9.566879      8142
1829                                   9.549669      1829
166                                    9.547170       166
3972                                   9.532258      3972
597                                    9.514286       597
486                                    9.508671       486
267                                    9.500000       267
4181                                   9.346384      4181
6114                                   9.331158      6114
10271                                  9.269360     10271
2952                                   9.257218      2952
1559                                   9.256803      1559
44                                     9.149871        44
5258                                   9.142857      5258

In [47]:
recommendation_df.tail(10)

          weighted average recommendation score  anime_id
anime_id
27741                                      -1.0     27741
27737                                      -1.0     27737
27727                                      -1.0     27727
27663                                      -1.0     27663
1500                                       -1.0      1500
27601                                      -1.0     27601
807                                        -1.0       807
13093                                      -1.0     13093
15409                                      -1.0     15409
24781                                      -1.0     24781